#!/usr/bin/python

import sys
import ZaUser
import keyChain
import json

#
# Keys and Url
#
zapyKey = "/home/lesds/.ZapyKeys/5e7e389b833f4bf4bdc9373e1d94c386.json"
zapyUrl = "https://64.191.192.72/zAccess/raadmin/webapi/doApi"

zaKeys = keyChain.keyChain(
   '/home/lesds/.ZapyKeys/ee4160675d6d4079b255a6aabaeadf3f.json', 
   'usae.zentera.net/zAccess'
)

#
# Instantiate a Default App Profile
#
print
print "Test ZaUser Create"

zu1 = ZaUser.ZaUser(zaKeys, 'Configs/cfgZaUser1.json')
zu1.syncWithController()
zu1.inspect()

zu2 = ZaUser.ZaUser(zaKeys, 'Configs/cfgZaUser2.json')
zu2.syncWithController()
zu2.inspect()

zu3 = ZaUser.ZaUser(zaKeys, 'Configs/cfgZaUser3.json')
zu3.syncWithController()
zu3.inspect()

#
# Test Delete User
#
raw_input('Ready to Delete Users? ')

zu1.ZaUser_delete()
zu2.ZaUser_delete()
zu3.ZaUser_delete()

print
print "Users Deleted"
print
