#!/usr/bin/python

import sys
import cloudDomain
import cloudServerPool
import json

#
# Keys and Url
#
zapiKey = "/home/lesds/.ZapyKeys/6b90a0ffc2c64499b43c41aa139bcfcd.json.txt"
zapyUrl = "https://64.191.192.72/zCenter/webapi/doApi"

#
# Instantiate a Default App Profile
#
print
print "Create a New Cloud Domain Object"
cd = cloudDomain.cloudDomain(
   cloudDomainName="myCloud",
   cloudConnector="AWS",
   iLikeFrogs="True"
)

cd.inspect()

sys.exit()

print
print "Create a New Cloud Server Pool Object"
sp = cloudServerPool.cloudServerPool()

#
# Attach the API Keys and URL
#
cd.loadKeys(zapiKey, zapyUrl)
sp.loadKeys(zapiKey, zapyUrl)

#
# Test the Customer Functions
#
cd.loadCfg("cfgCloudDomain.json")
cd.inspect()
cd.syncWithController()
cd.inspect()
cd.saveCfg("defCloudDomain.json")

# sp.set("poolTag", cd.CloudDomain_listCloudServerPools()['data'][0]['poolTag'])
# print '  ', sp.CloudServerPool_listEndServers('all')['data'][0]['hostname']
# print

#
# Delete
#
raw_input("Ready to Delete? ")

cd.CloudDomain_delete()
cd.inspect()
