#!/usr/bin/python

import sys
import zaUserGroup
import json

#
# Keys and Url
#
#zapiKey = "/home/lesds/.ZapyKeys/6b90a0ffc2c64499b43c41aa139bcfcd.json.txt"
#zapyUrl = "https://64.191.192.72/zCenter/webapi/doApi"
zapyKey = "/home/lesds/.ZapyKeys/5e7e389b833f4bf4bdc9373e1d94c386.json"
zapyUrl = "https://64.191.192.72/zaccess/raadmin/webapi/doApi"

#
# Instantiate a Default User Group
#
# print "Create a New User Group Object with Class Defaults"
ug = zaUserGroup.zaUserGroup()
ug.loadCfg('cfgZaUserGroup.json')

ip1 = "1.0.0.1"
ip2 = "1.0.1.1"
ip3 = "10.300.10.1"
ip4 = "192.30.10.1"
ip5 = "192.30.10.1/24"

print
print "{:15} == {}".format(ip1, ug.validateIpAddr(ip1))
print "{:15} == {}".format(ip2, ug.validateIpAddr(ip2))
print "{:15} == {}".format(ip3, ug.validateIpAddr(ip3))
print "{:15} == {}".format(ip4, ug.validateIpAddr(ip4))
print "{:15} == {}".format(ip5, ug.validateIpAddr(ip5))

print
print "From            <-> To              ==                 Dist"
print "{:15} <-> {:15} == {:20}".format(ip1, ip2, ug.distIpAddr(ip1, ip2))
print "{:15} <-> {:15} == {:20}".format(ip1, ip4, ug.distIpAddr(ip1, ip4))
print
