#!/usr/bin/python

import sys
import appProfile
import json

#
# Keys and Url
#
zapiKey = "/home/lesds/.ZapyKeys/6b90a0ffc2c64499b43c41aa139bcfcd.json.txt"
zapyUrl = "https://64.191.192.72/zCenter/webapi/doApi"

#
# Instantiate a Default App Profile
#
print "Create a New App Profile Object with Class Defaults"
ap = appProfile.appProfile()

#
# Attach the API Keys and URL
#
ap.loadKeys(zapiKey, zapyUrl)

#
# Test the Customer Functions
#
print ap.listCloudDomainsByName("LesDomain2")
print
print ap.getControllerSoftwareVersions()
print
print ap.getControllerLogDownloadUrl()
print
print ap.getControllerCertificate()
print
