#!/usr/bin/python

import sys
import ZaUserGroup
import keyChain
import json

#
# Keys and Url
#
zapyKey = "/home/lesds/.ZapyKeys/5e7e389b833f4bf4bdc9373e1d94c386.json"
zapyUrl = "https://64.191.192.72/zAccess/raadmin/webapi/doApi"

zaKeys = keyChain.keyChain(
   '/home/lesds/.ZapyKeys/ee4160675d6d4079b255a6aabaeadf3f.json', 
   'usae.zentera.net/zAccess'
)

#
# Instantiate a Default User Group
#
print
ug = ZaUserGroup.ZaUserGroup(zaKeys, 'Configs/cfgZaUserGroup.json')
print 'Create a New User Group', ug.get('groupName')
ug.syncWithController()
ug.inspect()

#
# Test Add User
#
print 'Adding Users to User Group'
ug.ZaUserGroup_addUser('lesds')
ug.ZaUserGroup_addUser('alex')

print
print 'List Users in', ug.get('groupName')
info =  ug.ZaUserGroup_listUsers()

for i in range(len(info['data'])):
   print '  ', info['data'][i]['account']

print

raw_input('Ready to Remove Users from User Group? ')

ug.ZaUserGroup_removeUser('lesds')

print
print 'List Users in', ug.get('groupName')
info =  ug.ZaUserGroup_listUsers()

for i in range(len(info['data'])):
   print '  ', info['data'][i]['account']

#
# Test Delete User Group
#
print
raw_input('Ready to Delete User Group? ')
ug.ZaUserGroup_delete()

print
print 'User Group Deleted'
print
