#!/usr/bin/python

"""
   Example Zapy Usage - Test the Basics of the Zapy Library

   Builds an App Profile for a Hybrid Environment

   Copyright (C) 2012-2018 Zentera Systems, Inc. - All Rights Reserved
"""

import sys
import zapyClass
import keyChain
import AppProfile
import CloudDomain
import CloudServerPool
import FabricServerPool
import ServerGroup
import CoipLan
import CoipWanTypeOne
import CoipWanTypeThree
import EndServer
import json

#
# Keys and Url
#
zcKeys = keyChain.keyChain(
   '/home/lesds/.ZapyKeys/a62b836b0b4e4ea6afbca04f18360bad.json', 
   'usae.zentera.net/zCenter'
)

#
# Instantiate a Default App Profile
#
print '\n===Create a New App Profile===================================================='
ap = AppProfile.AppProfile(zcKeys, 'Configs/LesProfileOneCfg.json')
ap.syncWithController()
ap.saveCfg('LesProfileOneDef.json')

#
# Cloud Domains
#
print '\n===Create New Cloud Domain 8==================================================='
cd8 = CloudDomain.CloudDomain(zcKeys, 'Configs/cfgCloudDomain8.json')
cd8.syncWithController()

print '\n===Create New Cloud Domain 9==================================================='
cd9 = CloudDomain.CloudDomain(zcKeys, 'Configs/cfgCloudDomain9.json')
cd9.syncWithController()

#
# Cloud Server Pools
#
print '\n===Create Cloud Server Pool 1=================================================='
sp1 = CloudServerPool.CloudServerPool(zcKeys, 'Configs/cfgCloudServerPool1.json')
sp1.syncWithController(cd8)

print '\n===Create Cloud Server Pool 2=================================================='
sp2 = CloudServerPool.CloudServerPool(zcKeys, 'Configs/cfgCloudServerPool2.json')
sp2.syncWithController(cd9)

#
# Fabric Server Pools
#
print '\n===Create Fabric Server Pool 1================================================='
fp1 = FabricServerPool.FabricServerPool(zcKeys, 'Configs/cfgFabricServerPool1.json')
fp1.syncWithController(cd8)

print '\n===Create Fabric Server Pool 2================================================='
fp2 = FabricServerPool.FabricServerPool(zcKeys, 'Configs/cfgFabricServerPool2.json')
fp2.syncWithController(cd9)

#
# Register the EndServers for the Edge Gateways
#
print '\n===Registering Edge Gateway 1=================================================='
eg1 = EndServer.EndServer(zcKeys, 'Configs/cfgEdgeGateway1.json')
eg1.EndServer_register()
eg1.inspect()

print '\n===Registering Edge Gateway 2=================================================='
eg2 = EndServer.EndServer(zcKeys, 'Configs/cfgEdgeGateway2.json')
eg2.EndServer_register()
eg2.inspect()

print '\n===Registering Edge Gateway 3=================================================='
eg3 = EndServer.EndServer(zcKeys, 'Configs/cfgEdgeGateway3.json')
eg3.EndServer_register()
eg3.inspect()

#
# Server Groups
#
print '\n===Create New Server Group 1==================================================='
g1 = ServerGroup.ServerGroup(zcKeys, 'Configs/cfgServerGroup1.json')
g1.syncWithController(ap, cd8, g1)

print '\n===Create New Server Group 2==================================================='
g2 = ServerGroup.ServerGroup(zcKeys, 'Configs/cfgServerGroup2.json')
g2.syncWithController(ap, cd8, g2)

print '\n===Create New Server Group 3==================================================='
g3 = ServerGroup.ServerGroup(zcKeys, 'Configs/cfgServerGroup3.json')
g3.syncWithController(ap, cd9, g3)

#
# CoIP Lan
#
print '\n===Create CoipLan=============================================================='
cl = CoipLan.CoipLan(zcKeys, 'Configs/cfgCoipLan.json')
cl.syncWithController(ap, g1, g2)

#
# CoIP Wans
#
print '\n===Create CoipWan Type One====================================================='
cw1 = CoipWanTypeOne.CoipWanTypeOne(zcKeys, 'Configs/cfgCoipWanTypeOne.json')
cw1.syncWithController(ap, g1, g3)

print '\n===Create CoipWan Type Two====================================================='
cw2 = CoipWanTypeTwo.CoipWanTypeTwo(zcKeys, 'Configs/cfgCoipWanTypeTwo.json')
cw2.syncWithController(ap, g2, g3)

print '\n===Create CoipWan Type Three==================================================='
cw3 = CoipWanTypeThree.CoipWanTypeThree(zcKeys, 'Configs/cfgCoipWanTypeThree.json')
cw3.syncWithController(ap, eg1, eg2)
cw3.inspect()

raw_input('Ready to Delete? ')

print
print '   Deleting App Profile'
ap.AppProfile_delete()

print '   Deleting Cloud Server Pools'
sp1.CloudServerPool_delete()
sp2.CloudServerPool_delete()

print '   Unregistering EndServers'
eg1.EndServer_unregister()
eg2.EndServer_unregister()

print '   Deleting Fabric Server Pools'
fp1.FabricServerPool_delete()
fp2.FabricServerPool_delete()

print '   Deleting Cloud Domains'
cd8.CloudDomain_delete()
cd9.CloudDomain_delete()

print
print 'Delete Complete'
print
